name: CSS (Dart Sass)
on: [push, pull_request]
env:
  CI: true
  NODE: 10.x

jobs:
  css:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "${{ env.NODE }}"

      - name: Set up npm cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v${{ env.NODE }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}-${{ hashFiles('.github/workflows/dart-sass.yml') }}
          restore-keys: |
            ${{ runner.OS }}-node-v${{ env.NODE }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}-${{ hashFiles('.github/workflows/dart-sass.yml') }}

      - name: Build CSS with Dart Sass
        run: |
          npx --ignore-existing sass --style expanded --source-map --embed-sources --no-error-css scss/:dist-sass/css/
          ls -Al dist-sass/css
